config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    # Add dashboard for your models here
    resources :users
    resources :insurances

    root 'users#index'
  end

  resources :users
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/insurance.rb
class Insurance < ApplicationRecord
  has_and_belongs_to_many :users, association_foreign_key: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :insurances, association_foreign_key: :insurance_id

  enum role: [:employee, :admin]
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin
    before_action :employee_access!

    def authenticate_admin
      current_user.admin?
    end

    def employee_access!
      if current_user.employee? && request.path.starts_with?('/admin')
        redirect_to root_path
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/insurances_controller.rb
module Admin
  class InsurancesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Pundit::Authorization
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:edit, :show, :update]
  def index
    @users = User.employee
  end

  def edit
    unless current_user == @user
      redirect_to root_path
      flash[:notice] = "You can only update your profile"
    end
  end

  def show
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "Your profile has been updated."
    else
      flash[:error] = @user.errors.join(' ')
    end
  end

  private

  def get_user
    @user  = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :date_of_birth,
      :accepted_terms,
      insurance_ids: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to "logout", destroy_user_session_path, method: :delete  %>
      <br>
      <% if current_user.admin? %>
        <%= link_to "Admin Panel", admin_root_path, method: :get %>
      <% end %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path(@user), method: :patch, local: true do |f| %>

  <%= f.text_field :first_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.email_field :email %><br>
  <%= f.date_field :date_of_birth %><br>
  <%= "Please accept terms and conditions." %>
  <%= f.check_box :accepted_terms %><br>
  <%= f.select(:insurance_ids, Insurance.all.collect {|i| [ i.title, i.id ] }, 
                                           { :prompt => "Please select"}, 
                                           { :multiple => true }) %><br>
  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1>Welcome Folks !!!!</h1>

<h3>Here is the list of employees </h3>
<ol>
  <% @users.each do |user| %>
    <li>
      <span> <b>Name:</b> <%= "#{user.first_name} #{user.last_name}"%> </span> |
      <span> <b>Email:</b> <%= user.email %> </span>
      <span> <b>Role:</b> <%= user.role %> </span>
      <span> <%= link_to 'Show', user_path(user) %> </span>
      <span> <%= link_to 'Update', edit_user_path(user) if current_user == user %> </span>
    </li>
  <% end %>
</ol>

app/views/users/show.html.erb
<h2>Details for User: <%= @user.first_name %></h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>